// ASCII level map for Act I. Each section is 23 rows of equal-length strings, joined left to right.
// Row 17 is the normal street surface (rows 17-22 are ground). Rows 0-8 are mostly sky.
// The last 6 columns of the map are empty: that is the fire chasm.
// Legend: see README (Milestone 8) and parseLevel.js. 'A' is where the angels' cinematic starts.

export const SODOM_SECTIONS = [
  {
    // the city before the destruction: flat ground, low walls and a few Sodomites to learn to jump and stomp.
    // Lot walks home; at his house ('A' in the next section) the angels come out and the city starts burning.
    name: 'Evening streets',
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '...................................bbbbbbbbbbbb.................',
      'bbbbbbbbbb.........................bbwbbbwbbwbb.................',
      'bbwbbbwbbb......bbbbbbbbbbbb.......bbbbbbbbbbbb........bbbbbbbbb',
      'bbbbbbbbbb......bbwbbbbwbbbb.......bbbbbbbbbbbb........bbwbbbwbb',
      'bbbbbbbbbb......bbbbbbbbbbbb......====bbbbbbbbb........bbbbbbbbb',
      'bbbbbbbbbb......bbbbbbbbbbbb.TTT...bbbbbbbbbbbb..TTTTT.bbbbbbbbb',
      'bbbbLbbbbb..TT..bbbbbbEbbbbb.BBB...bbbbbbbEbbbb.TBBBBB.bbbEbbbbb',
      '################################################################',
      '################################################################',
      '################################################################',
      '################################################################',
      '################################################################',
      '################################################################',
    ],
  },
  {
    name: 'Home street',
    rows: [
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      '........................................',
      'bbbbbbbb................................',
      'bbbbbbbb................................',
      'bwbbwbbb................................',
      'bbbbbbbb................................',
      'bbbbbbbb.............TTTTTTT............',
      'bbbbbbbb.............BBBBBBB............',
      'bbbbbbbb..A...PPPP...BBBBBBB.....V......',
      '########################################',
      '########################################',
      '########################################',
      '########################################',
      '########################################',
      '########################################',
    ],
  },
  {
    name: 'Market',
    rows: [
      '............................................................',
      '............................................................',
      '............................................................',
      '............................................................',
      '............................................................',
      '............................................................',
      '............................................................',
      '............................................................',
      '............................................................',
      '............................................................',
      '......bbbbbbbbbbbb........bbbbbbbbbbbbbb..........bbbbbbbbbb',
      '......bbbbbbbbbbbb........bbbbbbbbbbbbbb..........bbbbbbbbbb',
      '......bbwbbbbwbbbb........bbwbbbbbwbbbbb..........bbwbbbwbbb',
      '......bbbbbbbbbbbb........bbbbbbbbbbbbbb..........bbbbbbbbbb',
      '......bbbbbbbbbbb====.....bbbbbbbbbbbbbb..........bbbbbbbbbb',
      '....====bbb====bbb........bb====bbb====b..........bbbbbbbbbb',
      '......bbbbEbbbbbbb......V.bbbbbbbbbbbbbbE.....PPPPbbbbbVbbbb',
      '############################################################',
      '############################################################',
      '############################################################',
      '############################################################',
      '############################################################',
      '############################################################',
    ],
  },
  {
    name: 'Rooftops',
    rows: [
      '............................................................',
      '............................................................',
      '............................................................',
      '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbb.......................',
      '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbb...bbbbbbbbbbbbbb......',
      '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbb...bbbbbbbbbbbbbb......',
      '........bbbwbbbbwbbbbbbwbbbbbwbbbbwbb...bbbbbbbbbbbbbb......',
      '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbb...bbbwbbbbwbbbbb......',
      '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbb...bbbbbbbbbbbbbb......',
      '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbb...bbbbbbbbbbbbbb......',
      '........bbwbbbbbbbbbwbbbbbwbbbbbbbbbb...bbbbbbbbbbbbbb......',
      '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbb...bbbbbbbbbbbbbb......',
      '........bbbbbbbbbbbbbbbbbbbbbbbbbbbbb...bbbbbbbbbbbbbb......',
      '........bbbbbVbbbbbbbbbbbbbbEbbbbbbbb...TTTTTTT.............',
      '........TTTTTTTTTTTT...TTTTTTTTTTTTTT...BBBBBBB....TTTT.....',
      '......TTBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBB....BBBB.....',
      '....TTBBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBB....BBBBTT.C.',
      '####BBBBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBB....BBBBBB###',
      '####BBBBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBB....BBBBBB###',
      '####BBBBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBB....BBBBBB###',
      '####BBBBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBB....BBBBBB###',
      '####BBBBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBB....BBBBBB###',
      '####BBBBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBB....BBBBBB###',
    ],
  },
  {
    name: 'Collapsed quarter',
    rows: [
      '......................................................................',
      '......................................................................',
      '......................................................................',
      '......................................................................',
      '......................................................................',
      '......................................................................',
      '......................................................................',
      '......................................................................',
      '......................................................................',
      '......................................................................',
      '...........................................................H..........',
      'bbbbbbbbbbbbbb........................................................',
      'bbbbbbbbbbbbbb.....bbbbbbbbbbb........................................',
      'bbwbbbbbwbbbbb.bb..bbbbbbbbbbb......bbbbbbbbbbbb......................',
      'bbbbbbbbbbbbTTTTb..bbbwbbbbwbb......bbbwbbbbwbbb...........PP.........',
      'bbbbbbbbbTTTBBBBb..bbbbbbbbbbb......bbbbbbbbbbbb..TT..PPP......TT.....',
      'bbbbbEbTTBBBBBBBTT.bbbbbVbbbbb..PP..bbbbEbbbbbVbTTBB...........BBTT...',
      '#######BBBBBBBBBBB############..PP..############BBBB...........BBBB###',
      '#######BBBBBBBBBBB############..PP..############BBBB...........BBBB###',
      '#######BBBBBBBBBBB############..PP..############BBBB...........BBBB###',
      '#######BBBBBBBBBBB############..PP..############BBBB...........BBBB###',
      '#######BBBBBBBBBBB############..PP..############BBBB...........BBBB###',
      '#######BBBBBBBBBBB############..PP..############BBBB...........BBBB###',
    ],
  },
  {
    name: 'Temple of pillars',
    rows: [
      '......................................................................',
      '......................................................................',
      '......................................................................',
      '......................................................................',
      '......................................................................',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....',
      '......bbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbb.....',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....',
      '......bbbbbbbPPbbbbbbbbbbbbbEbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....',
      '......bbbbbPPPPbPPbbbbb###########bbbbbbb#######bbbbbbbbbbbbbbbbb.....',
      '......bbPPbPPPPbPPbPPb############bbPPPbb#########bbbbEbbPPPbbEbb...C.',
      '##################################.......#############################',
      '##################################.......#############################',
      '##################################.......#############################',
      '##################################.......#############################',
      '##################################.......#############################',
      '##################################.......#############################',
    ],
  },
  {
    name: 'High roofs',
    rows: [
      '......................................................................',
      '......................................................................',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.......',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.......',
      '......bbbwbbbbbwbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbb.......',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.......',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.......',
      '......bbbbbbbbbbbbbbbbb====bbbbbbbbb====bbbbbbbbbEbbbbbbbbbbbbb.......',
      '......bbbbbbbbbbbbbbHbVbbbbbbbbbbEbbbbVbbbbbbbTTTTTTTTTTTbbbbTTT......',
      '..................TTTTTTTTTT...TTTTTTTTTTTT...BBBBBBBBBBB....BBB......',
      '................TTBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB.==.BBB......',
      '..............TTBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBTT....',
      '............TTBBBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBBB....',
      '..........TTBBBBBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBBB....',
      '........TTBBBBBBBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBBBTT..',
      '......TTBBBBBBBBBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBBBBB..',
      '....TTBBBBBBBBBBBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBBBBBTT',
      '####BBBBBBBBBBBBBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBBBBBBB',
      '####BBBBBBBBBBBBBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBBBBBBB',
      '####BBBBBBBBBBBBBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBBBBBBB',
      '####BBBBBBBBBBBBBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBBBBBBB',
      '####BBBBBBBBBBBBBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBBBBBBB',
      '####BBBBBBBBBBBBBBBBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBB....BBBBBBBBB',
    ],
  },
  {
    name: 'City gate',
    rows: [
      '..........................................WWWWWWWWWWWWWWWW............',
      '..........................................WWWWWWWWWWWWWWWW............',
      '..........................................WWWWWWWWWWWWWWWW............',
      '..........................................WWWWWWWWWWWWWWWW............',
      '..........................................WWWWWWWWWWWWWWWW............',
      '..........................................WWWWWWWWWWWWWWWW............',
      '..........................................WWWWWWWWWWWWWWWW............',
      '..........................................WWWWWWWWWWWWWWWW............',
      '..........................................WWWWWWWWWWWWWWWW............',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.WWWWWWWWWWWWWWWW............',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbb............',
      'bbbbwbbbbbwbbbbbwbbbbbwbbbbbwbbbbbwbbbbbb.bbbbbbbbbbbbbbbb............',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbb............',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbb............',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbb............',
      'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbb............',
      'bbbbbbbbEbbbbbbbbbbbbbEbbbbbbPPPbbbbEbbbb.bbbbbbbbbbbbbbbb..G.........',
      '################################################################......',
      '################################################################......',
      '################################################################......',
      '################################################################......',
      '################################################################......',
      '################################################################......',
    ],
  },
];
